# Generated by Django 4.1.7 on 2023-02-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0004_alter_orderline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_cars.modelmake'),
        ),
    ]
