# Generated by Django 4.1.7 on 2023-02-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0005_modelmake_car_model_make'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={},
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, verbose_name='license plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_cars.modelmake', verbose_name='model and make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=17, verbose_name='VIN code'),
        ),
        migrations.AlterField(
            model_name='modelmake',
            name='make',
            field=models.CharField(max_length=255, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='modelmake',
            name='model',
            field=models.CharField(max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_cars.car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='order total'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='main_cars.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_cars.service', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price'),
        ),
    ]
