# Generated by Django 4.1.7 on 2023-02-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0006_alter_orderline_options_alter_car_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'paid'), ('n', 'waiting for payment')], default='p', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_cars.modelmake', verbose_name='car type'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_cars.service', verbose_name='service'),
        ),
    ]
