# Generated by Django 4.1.7 on 2023-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0007_order_status_alter_car_model_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmake',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='main_cars/covers/', verbose_name='car picture'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('w', 'Waiting for Authorization'), ('p', 'In progress'), ('c', 'Completed')], default='n', max_length=1, verbose_name='status'),
        ),
    ]
