# Generated by Django 4.1.7 on 2023-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0008_modelmake_cover_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmake',
            name='year',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='year'),
        ),
    ]
