# Generated by Django 4.1.7 on 2023-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0011_ordercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercomment',
            old_name='book',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='modelmake',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
