# Generated by Django 4.1.7 on 2023-03-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_cars', '0012_rename_book_ordercomment_order_alter_modelmake_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'orderline', 'verbose_name_plural': 'orderlines'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
